### ISSUE TITLE
Why use Sparrow over LLVM+SVF?

### ISSUE THREAD

**Issue by acidghost** [prosyslab/DAFL-artifact#2]
First, amazing work! Also thank you for open sourcing your project and providing extensive documentation.

I was wondering what was the reasoning for using Sparrow for static analysis instead of something based off LLVM; e.g. [SVF](https://github.com/SVF-tools/SVF/) is often used in fuzzing literature and works with C++ programs.

**Comment by goodtaeeun** [comment]
Hi, thank you for your interest in our work.

For the static analyzer, we chose the tool that was more familiar to us.
