### ISSUE TITLE
Error messages when trying to run run-smake.sh in the local environment

### ISSUE THREAD

**Issue by 5hEn918** [prosyslab/DAFL-artifact#6]
Hi
Recently I am working run DAFL on my local machine. When I tried to run run-smake.sh, some error messages occurs. But the smake-out  directory had some inputs. So I compared the inputs with the directory in the docker you provided, it seems the same (?).
Can I IGNORE this message?
![image](https://github.com/prosyslab/DAFL-artifact/assets/161289944/4aec5146-a8e1-466a-8df9-e68ece1384ca)

![image](https://github.com/prosyslab/DAFL-artifact/assets/161289944/07c40b50-e104-4c5b-8ce1-db7036e5a54e)

Here is part of the message
```
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:748: makeswf] Error 1
make[1]: Leaving directory '/benchmark/RUNDIR-libming-4.8.1/BUILD/util'
make: *** [Makefile:516: all-recursive] Error 
```

Also in my understanding, the run-smake.sh script will generate a series of .i fiels for each program and its target and put them in the smake-out directory, then the run_sparrow.py script will process the directory ang generate the DAFL-input directory, which contains dfg and functions folder. In my understanding the dfg folder contains the node score, which are instrumentd by AFL llvm pass. And the function folder contains the essential functions, which are also instrumented to give coverage feedback. Is it right?

**Comment by goodtaeeun** [comment]
Yes, you can ignore those messages.
Those error messages are emitted after building our binary of interest, `swftophp`, thus the necessary preprocessed files are successfully generated and copied into `smake-out`

**Comment by goodtaeeun** [comment]
And yes, your understanding is correct.

**Comment by 5hEn918** [comment]
Thanks for your time and response!

**Comment by 5hEn918** [comment]
Thanks for your time and response!
