### ISSUE TITLE
Help wanted when running the DAFL tool directly in the docker

### ISSUE THREAD

**Issue by null1024-ws** [prosyslab/DAFL-artifact#7]
Hi
So impressive the performance DAFL has in the directed fuzzing! Recently I tried to run the DAFL in the provided docker using "run-DAFL.sh" script, there is something wrong with the fuzzing instance. 
The command I used is `sudo ./run_DAFL.sh lrzip-ed51e14-2018-11496  "-A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D @@" "file" 60
`, the figure containing the error messages is as below.
![image](https://github.com/prosyslab/DAFL-artifact/assets/79917102/3ffb5650-c7b5-4cc8-82fc-12ffe9cb9516)
The fuzzing testing process was aborted by something. The ./common-postproc.sh is in the same directory.
So could you kindly help with this?

**Comment by goodtaeeun** [comment]
Hi, thank you for your interest in DAFL and its artifact!

Try running the script with the absolute path as the following.
`/tool-script/run_DAFL.sh lrzip-ed51e14-2018-11496  "-A -a -l -S -s --special-syms --synthetic --with-symbol-versions -D @@" "file" 60`

**Comment by null1024-ws** [comment]
Thanks for your advice.  I tried this command in the docker environment. There was no problem like "No such file or directory". But the fuzzing instance seemed something abnormal.
The total paths always 1;
![image](https://github.com/prosyslab/DAFL-artifact/assets/79917102/514e8adc-2cb8-4f42-80fd-f5f400c589e0)

**Comment by goodtaeeun** [comment]
The current command line options you are using are for `nm`, not `lrzip`.
You can find the appropriate command line options in `scripts/benchmark.py`.
For instance, you should use `-t @@` for `lrzip` 
https://github.com/prosyslab/DAFL-artifact/blob/963f46fa147901cbb114be7aecb8f4fc375ae941/scripts/benchmark.py#L24

**Comment by null1024-ws** [comment]
Thanks for pointing out my mistake.

**Comment by null1024-ws** [comment]
Thanks for pointing out my mistake.
